repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Pin to a specific version; update as needed.
    hooks:
      - id: black
        args: ["--line-length", "180"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Pin to a specific version; update as needed.
    hooks:
      - id: isort
